# Generated by Django 6.0.5 on 2026-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Authenticated User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
